//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLAzureDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateStatu
    {
        public CandidateStatu()
        {
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int CandidateStatusId { get; set; }
        public string CandidateStatusName { get; set; }
    
        public virtual ICollection<Candidate> Candidates { get; set; }
    }
}
